services:
  - type: web
    name: j-score
    env: python
    branch: main
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    autoDeploy: true
    plan: starter
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        value: "replace_with_a_secret_key"
